route:
  repeat_interval: 15s # Time interval between consecutive notifications for the same alert
  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1449362830976483378/JR5LRc_Is_DKVsmPXTx8ooe7-6XZgZEDKXaUOTaswQ10EP9maOMgcesO4KwBLmTunCo5